yfinance (installed)

In [1]:
# pip install yfinance

yfinance API

In [4]:
import pandas as pd
import yfinance as yf

NVDA = yf.Ticker("NVDA")

NVDA.info

{'address1': '2788 San Tomas Expressway',
 'city': 'Santa Clara',
 'state': 'CA',
 'zip': '95051',
 'country': 'United States',
 'phone': '408 486 2000',
 'website': 'https://www.nvidia.com',
 'industry': 'Semiconductors',
 'industryKey': 'semiconductors',
 'industryDisp': 'Semiconductors',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': "NVIDIA Corporation provides graphics and compute and networking solutions in the United States, Taiwan, China, Hong Kong, and internationally. The Graphics segment offers GeForce GPUs for gaming and PCs, the GeForce NOW game streaming service and related infrastructure, and solutions for gaming platforms; Quadro/NVIDIA RTX GPUs for enterprise workstation graphics; virtual GPU or vGPU software for cloud-based visual and virtual computing; automotive platforms for infotainment systems; and Omniverse software for building and operating metaverse and 3D internet applications. The Compute & Networking segment comprises Data Center computing platforms and end-to-end networking platforms, including Quantum for InfiniBand and Spectrum for Ethernet; NVIDIA DRIVE automated-driving platform and automotive development agreements; Jetson robotics and other embedded platforms; NVIDIA AI Enterprise and other software; and DGX Cloud software and services. The company's products are used in gaming, professional visualization, data center, and automotive markets. It sells its products to original equipment manufacturers, original device manufacturers, system integrators and distributors, independent software vendors, cloud service providers, consumer internet companies, add-in board manufacturers, distributors, automotive manufacturers and tier-1 automotive suppliers, and other ecosystem participants. NVIDIA Corporation was incorporated in 1993 and is headquartered in Santa Clara, California.",
 'fullTimeEmployees': 29600,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Jen-Hsun  Huang',
   'age': 60,
   'title': 'Co-Founder, CEO, President & Director',
   'yearBorn': 1963,
   'fiscalYear': 2024,
   'totalPay': 7491487,
   'exercisedValue': 217327152,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Colette M. Kress',
   'age': 56,
   'title': 'Executive VP & CFO',
   'yearBorn': 1967,
   'fiscalYear': 2024,
   'totalPay': 1510765,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Debora  Shoquist',
   'age': 68,
   'title': 'Executive Vice President of Operations',
   'yearBorn': 1955,
   'fiscalYear': 2024,
   'totalPay': 1371266,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ajay K. Puri',
   'age': 68,
   'title': 'Executive Vice President of Worldwide Field Operations',
   'yearBorn': 1955,
   'fiscalYear': 2024,
   'totalPay': 2295097,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Chris A. Malachowsky',
   'title': 'Co-Founder',
   'fiscalYear': 2024,
   'totalPay': 320000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Donald F. Robertson Jr.',
   'age': 54,
   'title': 'VP & Chief Accounting Officer',
   'yearBorn': 1969,
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Prof. William J. Dally Ph.D.',
   'age': 62,
   'title': 'Chief Scientist & Senior VP of Research',
   'yearBorn': 1961,
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Mylene  Mangalindan',
   'title': 'VP of Corporate Communications',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Tommy  Lee',
   'title': 'Senior Vice President of Systems Engineering & Application',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Brian M. Kelleher',
   'title': 'Senior Vice President of Hardware Engineering',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 7,
 'boardRisk': 10,
 'compensationRisk': 5,
 'shareHolderRightsRisk': 6,
 'overallRisk': 8,
 'governanceEpochDate': 1730419200,
 'compensationAsOfEpochDate': 1735603200,
 'irWebsite': 'http://phx.corporate-ir.net/phoenix.zhtml?c=116466&p=irol-IRHome',
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 146.76,
 'open': 144.87,
 'dayLow': 140.08,
 'dayHigh': 145.24,
 'regularMarketPreviousClose': 146.76,
 'regularMarketOpen': 144.87,
 'regularMarketDayLow': 140.08,
 'regularMarketDayHigh': 145.24,
 'dividendRate': 0.04,
 'dividendYield': 0.00029999999,
 'exDividendDate': 1726099200,
 'payoutRatio': 0.010299999,
 'fiveYearAvgDividendYield': 0.09,
 'beta': 1.657,
 'trailingPE': 68.92233,
 'forwardPE': 33.96025,
 'volume': 248500046,
 'regularMarketVolume': 248500046,
 'averageVolume': 274101575,
 'averageVolume10days': 198954550,
 'averageDailyVolume10Day': 198954550,
 'bid': 141.97,
 'ask': 142.18,
 'bidSize': 100,
 'askSize': 300,
 'marketCap': 3600016474112,
 'fiftyTwoWeekLow': 45.01,
 'fiftyTwoWeekHigh': 149.77,
 'priceToSalesTrailing12Months': 37.38063,
 'fiftyDayAverage': 130.9676,
 'twoHundredDayAverage': 108.88873,
 'trailingAnnualDividendRate': 0.022,
 'trailingAnnualDividendYield': 0.0001499046,
 'currency': 'USD',
 'enterpriseValue': 3457984495616,
 'profitMargins': 0.55041003,
 'floatShares': 23541441000,
 'sharesOutstanding': 24529999872,
 'sharesShort': 246400791,
 'sharesShortPriorMonth': 251090067,
 'sharesShortPreviousMonthDate': 1727654400,
 'dateShortInterest': 1730332800,
 'sharesPercentSharesOut': 0.01,
 'heldPercentInsiders': 0.0429,
 'heldPercentInstitutions': 0.66152,
 'shortRatio': 1.01,
 'shortPercentOfFloat': 0.0105,
 'impliedSharesOutstanding': 25355800576,
 'bookValue': 2.368,
 'priceToBook': 59.957767,
 'lastFiscalYearEnd': 1706400000,
 'nextFiscalYearEnd': 1738022400,
 'mostRecentQuarter': 1722124800,
 'earningsQuarterlyGrowth': 1.682,
 'netIncomeToCommon': 53007998976,
 'trailingEps': 2.06,
 'forwardEps': 4.12,
 'lastSplitFactor': '10:1',
 'lastSplitDate': 1717977600,
 'enterpriseToRevenue': 35.906,
 'enterpriseToEbitda': 56.518,
 '52WeekChange': 1.8165605,
 'SandP52WeekChange': 0.29098952,
 'lastDividendValue': 0.01,
 'lastDividendDate': 1726099200,
 'exchange': 'NMS',
 'quoteType': 'EQUITY',
 'symbol': 'NVDA',
 'underlyingSymbol': 'NVDA',
 'shortName': 'NVIDIA Corporation',
 'longName': 'NVIDIA Corporation',
 'firstTradeDateEpochUtc': 917015400,
 'timeZoneFullName': 'America/New_York',
 'timeZoneShortName': 'EST',
 'uuid': '7f5f6a07-b148-30f4-98a2-2caa3df2aed0',
 'messageBoardId': 'finmb_32307',
 'gmtOffSetMilliseconds': -18000000,
 'currentPrice': 141.98,
 'targetHighPrice': 200.0,
 'targetLowPrice': 90.0,
 'targetMeanPrice': 158.98755,
 'targetMedianPrice': 164.0,
 'recommendationMean': 1.28571,
 'recommendationKey': 'strong_buy',
 'numberOfAnalystOpinions': 53,
 'totalCash': 34800001024,
 'totalCashPerShare': 1.419,
 'ebitda': 61184000000,
 'totalDebt': 10014999552,
 'quickRatio': 3.503,
 'currentRatio': 4.269,
 'totalRevenue': 96307003392,
 'debtToEquity': 17.221,
 'revenuePerShare': 3.91,
 'returnOnAssets': 0.55258,
 'returnOnEquity': 1.23767,
 'freeCashflow': 33725874176,
 'operatingCashflow': 48663998464,
 'earningsGrowth': 1.68,
 'revenueGrowth': 1.224,
 'grossMargins': 0.75975996,
 'ebitdaMargins': 0.6353,
 'operatingMargins': 0.62057,
 'financialCurrency': 'USD',
 'trailingPegRatio': 1.0915}

In [5]:
NVDA.major_holders

c:\Users\FBE RPG\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:530: RuntimeWarning: invalid value encountered in cast
  arr, tz_parsed = tslib.array_with_unit_to_datetime(arg, unit, errors=errors)

Breakdown                          Value
insidersPercentHeld              0.04290
institutionsPercentHeld          0.66152
institutionsFloatPercentHeld     0.69118
institutionsCount             5933.00000

In [6]:
NVDA.institutional_holders

,Date Reported,Holder,pctHeld,Shares,Value
0,2024-03-31,Vanguard Group Inc,0.8672,2133356260,192761538228
1,2024-03-31,Blackrock Inc.,0.7408,1822389250,164663803073
2,2024-03-31,"FMR, LLC",0.4679,1151036980,104003097364
3,2024-03-31,State Street Corporation,0.3678,904894170,81762617624
4,2024-03-31,"Geode Capital Management, LLC",0.2134,524942990,47431748804
5,2024-03-31,Price (T.Rowe) Associates Inc,0.1876,461499100,41699212679
6,2024-03-31,JP Morgan Chase & Company,0.1543,379614540,34300451376
7,2024-03-31,Morgan Stanley,0.1377,338760640,30609056387
8,2023-12-31,Norges Bank Investment Management,0.1199,294947080,14606369295
9,2024-03-31,Northern Trust Corporation,0.0986,242517530,21912913940

In [7]:
NVDA.actions

                           Dividends  Stock Splits
Date
2000-06-27 00:00:00-04:00   0.000000           2.0
2001-09-10 00:00:00-04:00   0.000000           2.0
2006-04-07 00:00:00-04:00   0.000000           2.0
2007-09-11 00:00:00-04:00   0.000000           1.5
2012-11-20 00:00:00-05:00   0.001875           0.0
2013-02-26 00:00:00-05:00   0.001875           0.0
2013-05-21 00:00:00-04:00   0.001875           0.0
2013-08-20 00:00:00-04:00   0.001875           0.0
2013-11-19 00:00:00-05:00   0.002125           0.0
2014-02-25 00:00:00-05:00   0.002125           0.0
2014-05-20 00:00:00-04:00   0.002125           0.0
2014-08-19 00:00:00-04:00   0.002125           0.0
2014-11-19 00:00:00-05:00   0.002125           0.0
2015-02-24 00:00:00-05:00   0.002125           0.0
2015-05-19 00:00:00-04:00   0.002450           0.0
2015-08-18 00:00:00-04:00   0.002450           0.0
2015-11-18 00:00:00-05:00   0.002875           0.0
2016-02-29 00:00:00-05:00   0.002875           0.0
2016-05-24 00:00:00-04:00   0.002875           0.0
2016-08-23 00:00:00-04:00   0.002875           0.0
2016-11-23 00:00:00-05:00   0.003500           0.0
2017-02-22 00:00:00-05:00   0.003500           0.0
2017-05-19 00:00:00-04:00   0.003500           0.0
2017-08-22 00:00:00-04:00   0.003500           0.0
2017-11-22 00:00:00-05:00   0.003750           0.0
2018-02-22 00:00:00-05:00   0.003750           0.0
2018-05-23 00:00:00-04:00   0.003750           0.0
2018-08-29 00:00:00-04:00   0.003750           0.0
2018-11-29 00:00:00-05:00   0.004000           0.0
2019-02-28 00:00:00-05:00   0.004000           0.0
2019-05-30 00:00:00-04:00   0.004000           0.0
2019-08-28 00:00:00-04:00   0.004000           0.0
2019-11-27 00:00:00-05:00   0.004000           0.0
2020-02-27 00:00:00-05:00   0.004000           0.0
2020-06-04 00:00:00-04:00   0.004000           0.0
2020-09-01 00:00:00-04:00   0.004000           0.0
2020-12-03 00:00:00-05:00   0.004000           0.0
2021-03-09 00:00:00-05:00   0.004000           0.0
2021-06-09 00:00:00-04:00   0.004000           0.0
2021-07-20 00:00:00-04:00   0.000000           4.0
2021-08-31 00:00:00-04:00   0.004000           0.0
2021-12-01 00:00:00-05:00   0.004000           0.0
2022-03-02 00:00:00-05:00   0.004000           0.0
2022-06-08 00:00:00-04:00   0.004000           0.0
2022-09-07 00:00:00-04:00   0.004000           0.0
2022-11-30 00:00:00-05:00   0.004000           0.0
2023-03-07 00:00:00-05:00   0.004000           0.0
2023-06-07 00:00:00-04:00   0.004000           0.0
2023-09-06 00:00:00-04:00   0.004000           0.0
2023-12-05 00:00:00-05:00   0.004000           0.0
2024-03-05 00:00:00-05:00   0.004000           0.0
2024-06-10 00:00:00-04:00   0.000000          10.0
2024-06-11 00:00:00-04:00   0.010000           0.0
2024-09-12 00:00:00-04:00   0.010000           0.0

In [8]:
NVDA.dividends

Date
2012-11-20 00:00:00-05:00    0.001875
2013-02-26 00:00:00-05:00    0.001875
2013-05-21 00:00:00-04:00    0.001875
2013-08-20 00:00:00-04:00    0.001875
2013-11-19 00:00:00-05:00    0.002125
2014-02-25 00:00:00-05:00    0.002125
2014-05-20 00:00:00-04:00    0.002125
2014-08-19 00:00:00-04:00    0.002125
2014-11-19 00:00:00-05:00    0.002125
2015-02-24 00:00:00-05:00    0.002125
2015-05-19 00:00:00-04:00    0.002450
2015-08-18 00:00:00-04:00    0.002450
2015-11-18 00:00:00-05:00    0.002875
2016-02-29 00:00:00-05:00    0.002875
2016-05-24 00:00:00-04:00    0.002875
2016-08-23 00:00:00-04:00    0.002875
2016-11-23 00:00:00-05:00    0.003500
2017-02-22 00:00:00-05:00    0.003500
2017-05-19 00:00:00-04:00    0.003500
2017-08-22 00:00:00-04:00    0.003500
2017-11-22 00:00:00-05:00    0.003750
2018-02-22 00:00:00-05:00    0.003750
2018-05-23 00:00:00-04:00    0.003750
2018-08-29 00:00:00-04:00    0.003750
2018-11-29 00:00:00-05:00    0.004000
2019-02-28 00:00:00-05:00    0.004000
2019-05-30 00:00:00-04:00    0.004000
2019-08-28 00:00:00-04:00    0.004000
2019-11-27 00:00:00-05:00    0.004000
2020-02-27 00:00:00-05:00    0.004000
2020-06-04 00:00:00-04:00    0.004000
2020-09-01 00:00:00-04:00    0.004000
2020-12-03 00:00:00-05:00    0.004000
2021-03-09 00:00:00-05:00    0.004000
2021-06-09 00:00:00-04:00    0.004000
2021-08-31 00:00:00-04:00    0.004000
2021-12-01 00:00:00-05:00    0.004000
2022-03-02 00:00:00-05:00    0.004000
2022-06-08 00:00:00-04:00    0.004000
2022-09-07 00:00:00-04:00    0.004000
2022-11-30 00:00:00-05:00    0.004000
2023-03-07 00:00:00-05:00    0.004000
2023-06-07 00:00:00-04:00    0.004000
2023-09-06 00:00:00-04:00    0.004000
2023-12-05 00:00:00-05:00    0.004000
2024-03-05 00:00:00-05:00    0.004000
2024-06-11 00:00:00-04:00    0.010000
2024-09-12 00:00:00-04:00    0.010000
Name: Dividends, dtype: float64

In [9]:
NVDA.splits

Date
2000-06-27 00:00:00-04:00     2.0
2001-09-10 00:00:00-04:00     2.0
2006-04-07 00:00:00-04:00     2.0
2007-09-11 00:00:00-04:00     1.5
2021-07-20 00:00:00-04:00     4.0
2024-06-10 00:00:00-04:00    10.0
Name: Stock Splits, dtype: float64

Financial statements

In [10]:
NVDA.financials

,2024-01-31,2023-01-31,2022-01-31,2021-01-31
Tax Effect Of Unusual Items,0.0,-284130000.0,0.0,0.0
Tax Rate For Calcs,0.12,0.21,0.019,0.017
Normalized EBITDA,35583000000.0,7340000000.0,11351000000.0,5691000000.0
Total Unusual Items,0.0,-1353000000.0,0.0,0.0
Total Unusual Items Excluding Goodwill,0.0,-1353000000.0,0.0,0.0
Net Income From Continuing Operation Net Minority Interest,29760000000.0,4368000000.0,9752000000.0,4332000000.0
Reconciled Depreciation,1508000000.0,1544000000.0,1174000000.0,1098000000.0
Reconciled Cost Of Revenue,16621000000.0,11618000000.0,9439000000.0,6279000000.0
EBITDA,35583000000.0,5987000000.0,11351000000.0,5691000000.0
EBIT,34075000000.0,4443000000.0,10177000000.0,4593000000.0
Net Interest Income,609000000.0,5000000.0,-207000000.0,-127000000.0
Interest Expense,257000000.0,262000000.0,236000000.0,184000000.0
Interest Income,866000000.0,267000000.0,29000000.0,57000000.0
Normalized Income,29760000000.0,5436870000.0,9752000000.0,4332000000.0
Net Income From Continuing And Discontinued Operation,29760000000.0,4368000000.0,9752000000.0,4332000000.0
Total Expenses,27950000000.0,21397000000.0,16873000000.0,12143000000.0
Total Operating Income As Reported,32972000000.0,4224000000.0,10041000000.0,4532000000.0
Diluted Average Shares,24940000000.0,25070000000.0,25350000000.0,25120000000.0
Basic Average Shares,24690000000.0,24870000000.0,24960000000.0,24680000000.0
Diluted EPS,1.193,0.174,0.385,0.1725
Basic EPS,1.205,0.176,0.391,0.1755
Diluted NI Availto Com Stockholders,29760000000.0,4368000000.0,9752000000.0,4332000000.0
Net Income Common Stockholders,29760000000.0,4368000000.0,9752000000.0,4332000000.0
Net Income,29760000000.0,4368000000.0,9752000000.0,4332000000.0
Net Income Including Noncontrolling Interests,29760000000.0,4368000000.0,9752000000.0,4332000000.0
Net Income Continuous Operations,29760000000.0,4368000000.0,9752000000.0,4332000000.0
Tax Provision,4058000000.0,-187000000.0,189000000.0,77000000.0
Pretax Income,33818000000.0,4181000000.0,9941000000.0,4409000000.0
Other Income Expense,237000000.0,-1401000000.0,107000000.0,4000000.0
Other Non Operating Income Expenses,237000000.0,-48000000.0,107000000.0,4000000.0
Special Income Charges,0.0,-1353000000.0,0.0,0.0
Restructuring And Mergern Acquisition,0.0,1353000000.0,0.0,0.0
Net Non Operating Interest Income Expense,609000000.0,5000000.0,-207000000.0,-127000000.0
Interest Expense Non Operating,257000000.0,262000000.0,236000000.0,184000000.0
Interest Income Non Operating,866000000.0,267000000.0,29000000.0,57000000.0
Operating Income,32972000000.0,5577000000.0,10041000000.0,4532000000.0
Operating Expense,11329000000.0,9779000000.0,7434000000.0,5864000000.0
Research And Development,8675000000.0,7339000000.0,5268000000.0,3924000000.0
Selling General And Administration,2654000000.0,2440000000.0,2166000000.0,1940000000.0
Gross Profit,44301000000.0,15356000000.0,17475000000.0,10396000000.0
Cost Of Revenue,16621000000.0,11618000000.0,9439000000.0,6279000000.0
Total Revenue,60922000000.0,26974000000.0,26914000000.0,16675000000.0
Operating Revenue,60922000000.0,26974000000.0,26914000000.0,16675000000.0

In [11]:
NVDA.balancesheet

,2024-01-31,2023-01-31,2022-01-31,2021-01-31,2020-01-31
Treasury Shares Number,NaN,NaN,NaN,13800000000.0,13700576960.0
Ordinary Shares Number,24640000000.0,24661365720.0,25060000000.0,24800000000.0,NaN
Share Issued,24640000000.0,24661365720.0,25060000000.0,38600000000.0,NaN
Net Debt,2429000000.0,7564000000.0,8956000000.0,6116000000.0,NaN
Total Debt,11056000000.0,12031000000.0,11831000000.0,7597000000.0,NaN
...,...,...,...,...,...
Allowance For Doubtful Accounts Receivable,NaN,NaN,NaN,-21000000.0,-11000000.0
Gross Accounts Receivable,NaN,NaN,NaN,2450000000.0,1668000000.0
Cash Cash Equivalents And Short Term Investments,25984000000.0,13296000000.0,21208000000.0,11561000000.0,NaN
Other Short Term Investments,18704000000.0,9907000000.0,19218000000.0,10714000000.0,NaN
Cash And Cash Equivalents,7280000000.0,3389000000.0,1990000000.0,847000000.0,NaN

In [12]:
NVDA.cashflow

,2024-01-31,2023-01-31,2022-01-31,2021-01-31,2020-01-31
Free Cash Flow,27021000000.0,3808000000.0,8132000000.0,4694000000.0,NaN
Repurchase Of Capital Stock,-9533000000.0,-10039000000.0,0.0,0.0,NaN
Repayment Of Debt,-1250000000.0,0.0,-1000000000.0,0.0,NaN
Issuance Of Debt,0.0,0.0,4977000000.0,4968000000.0,NaN
Capital Expenditure,-1069000000.0,-1833000000.0,-976000000.0,-1128000000.0,NaN
Interest Paid Supplemental Data,252000000.0,254000000.0,246000000.0,138000000.0,NaN
Income Tax Paid Supplemental Data,6549000000.0,1404000000.0,396000000.0,249000000.0,NaN
End Cash Position,7280000000.0,3389000000.0,1990000000.0,847000000.0,NaN
Beginning Cash Position,3389000000.0,1990000000.0,847000000.0,10896000000.0,NaN
Changes In Cash,3891000000.0,1399000000.0,1143000000.0,-10049000000.0,NaN
Financing Cash Flow,-13633000000.0,-11617000000.0,1865000000.0,3804000000.0,NaN
Cash Flow From Continuing Financing Activities,-13633000000.0,-11617000000.0,1865000000.0,3804000000.0,NaN
Net Other Financing Charges,-2858000000.0,-1535000000.0,-1994000000.0,-963000000.0,NaN
Proceeds From Stock Option Exercised,403000000.0,355000000.0,281000000.0,194000000.0,NaN
Cash Dividends Paid,-395000000.0,-398000000.0,-399000000.0,-395000000.0,NaN
Common Stock Dividend Paid,NaN,-398000000.0,-399000000.0,-395000000.0,-390000000.0
Net Common Stock Issuance,-9533000000.0,-10039000000.0,0.0,0.0,NaN
Common Stock Payments,-9533000000.0,-10039000000.0,0.0,0.0,NaN
Net Issuance Payments Of Debt,-1250000000.0,0.0,3977000000.0,4968000000.0,NaN
Net Long Term Debt Issuance,-1250000000.0,0.0,3977000000.0,4968000000.0,NaN
Long Term Debt Payments,-1250000000.0,0.0,-1000000000.0,0.0,NaN
Long Term Debt Issuance,0.0,0.0,4977000000.0,4968000000.0,NaN
Investing Cash Flow,-10566000000.0,7375000000.0,-9830000000.0,-19675000000.0,NaN
Cash Flow From Continuing Investing Activities,-10566000000.0,7375000000.0,-9830000000.0,-19675000000.0,NaN
Net Investment Purchase And Sale,-9414000000.0,9257000000.0,-8591000000.0,-10023000000.0,NaN
Sale Of Investment,9782000000.0,21231000000.0,16220000000.0,9319000000.0,NaN
Purchase Of Investment,-19196000000.0,-11974000000.0,-24811000000.0,-19342000000.0,NaN
Net Business Purchase And Sale,-83000000.0,-49000000.0,-263000000.0,-8524000000.0,NaN
Purchase Of Business,-83000000.0,-49000000.0,-263000000.0,-8524000000.0,NaN
Net PPE Purchase And Sale,-1069000000.0,-1833000000.0,-976000000.0,-1128000000.0,NaN
Sale Of PPE,NaN,NaN,NaN,NaN,0.0
Purchase Of PPE,-1069000000.0,-1833000000.0,-976000000.0,-1128000000.0,NaN
Capital Expenditure Reported,NaN,NaN,NaN,-1128000000.0,-489000000.0
Operating Cash Flow,28090000000.0,5641000000.0,9108000000.0,5822000000.0,NaN
Cash Flow From Continuing Operating Activities,28090000000.0,5641000000.0,9108000000.0,5822000000.0,NaN
Change In Working Capital,-3722000000.0,-2207000000.0,-3363000000.0,-703000000.0,NaN
Change In Other Working Capital,NaN,NaN,NaN,163000000.0,28000000.0
Change In Other Current Liabilities,514000000.0,252000000.0,192000000.0,163000000.0,NaN
Change In Payables And Accrued Expense,3556000000.0,790000000.0,1149000000.0,602000000.0,NaN
Change In Accrued Expense,2025000000.0,1341000000.0,581000000.0,290000000.0,NaN
Change In Payable,1531000000.0,-551000000.0,568000000.0,312000000.0,NaN
Change In Account Payable,1531000000.0,-551000000.0,568000000.0,312000000.0,NaN
Change In Prepaid Assets,-1522000000.0,-1517000000.0,-1715000000.0,-394000000.0,NaN
Change In Inventory,-98000000.0,-2554000000.0,-774000000.0,-524000000.0,NaN
Change In Receivables,-6172000000.0,822000000.0,-2215000000.0,-550000000.0,NaN
Changes In Account Receivables,-6172000000.0,822000000.0,-2215000000.0,-550000000.0,NaN
Other Non Cash Items,-278000000.0,1346000000.0,47000000.0,-20000000.0,NaN
Stock Based Compensation,3549000000.0,2709000000.0,2004000000.0,1397000000.0,NaN
Deferred Tax,-2489000000.0,-2164000000.0,-406000000.0,-282000000.0,NaN
Deferred Income Tax,-2489000000.0,-2164000000.0,-406000000.0,-282000000.0,NaN
Depreciation Amortization Depletion,1508000000.0,1544000000.0,1174000000.0,1098000000.0,NaN
Depreciation And Amortization,1508000000.0,1544000000.0,1174000000.0,1098000000.0,NaN
Operating Gains Losses,-238000000.0,45000000.0,-100000000.0,NaN,1000000.0
Gain Loss On Investment Securities,-238000000.0,45000000.0,-100000000.0,NaN,1000000.0
Net Income From Continuing Operations,29760000000.0,4368000000.0,9752000000.0,4332000000.0,NaN